<a href="https://colab.research.google.com/github/laxitabaheti/ColabPythonDemo/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([[1],
              [2]])
print(arr)


[[1]
 [2]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4],ndmin=4)
print(arr)
print(arr.ndim)
print(arr.dtype)


x= arr.copy()
y=arr.view()
print(x)
print(y)


[[[[1 2 3 4]]]]
4
int64
[[[[1 2 3 4]]]]
[[[[1 2 3 4]]]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:,3])
print(arr[0:2,0:3])


[4 9]
[[1 2 3]
 [6 7 8]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)

print('shape of array :', arr.shape)


[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=7)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[[[1 2 3 4]]]]]]]
number of dimensions : 7


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]])
 
for x in arr:
  for y in x:
    for z in y:
      print (z)
      

1
2
3
2
3
4
3
4
5
4
5
6


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]])
 
for x in np.nditer(arr):
  print(x)
  

1
2
3
2
3
4
3
4
5
4
5
6


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [ ]:
import numpy as np

arr1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

arr2 = np.array ([[[9,10],[11,12]],[[13,14],[15,16]]])

arr3=np.concatenate((arr1,arr2),axis=0)
arr4=np.concatenate((arr1,arr2),axis=1)
arr5=np.concatenate((arr1,arr2),axis=2)


print(arr3)
print(arr4)
print(arr5)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]
[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


In [ ]:
import numpy as np
arr1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

arr2 = np.array ([[[9,10],[11,12]],[[13,14],[15,16]]])

arrA=np.hstack((arr1,arr2))
arrB=np.vstack((arr1,arr2))
arrC=np.dstack((arr1,arr2))

print(arrA.shape)
print(arrA)
print(arrB.shape)
print(arrB)
print(arrC.shape)
print(arrC)


(2, 4, 2)
[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]
(4, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(2, 2, 4)
[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


In [ ]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])

arr2 = np.array ([[9,10],[11,12]])

arr=np.vstack((arr1,arr2))
print(arr1)
print(arr2)
print(arr)
print(arr1.shape)
print(arr2.shape)
print(arr.shape)


[[1 2]
 [3 4]]
[[ 9 10]
 [11 12]]
[[ 1  2]
 [ 3  4]
 [ 9 10]
 [11 12]]
(2, 2)
(2, 2)
(4, 2)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)
y = np.where(arr%2 == 1)

print(x)
print(y)


(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)


In [ ]:
import numpy as np

arr = np.array([
                [1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9], 
                [10, 11, 12], 
                [13, 14, 15], 
                [16, 17, 18]
                ])

newarr = np.array_split(arr,2)

print(newarr) 


[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr.shape)


(6, 3)


In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)


[41 43]


In [ ]:
import numpy as np
arr=np.array([1,-2,3,-4,5,-6,7])
arr1=arr>0
arr2 = arr[arr1]
print(arr1)
print(arr2)


[ True False  True False  True False  True]
[1 3 5 7]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.reshape(3,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
import numpy as np

a=np.linspace(1,10,100)
print(a)


[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.max())
print(arr.min())
print(arr.sum())


12
1
78


In [ ]:

from numpy import random

ll= random.randint(2)
print(ll)
kk= random.rand()
print(kk)
mm= random.randint(200,size=(1,6))
print(mm)
nn= random.rand(2,6)
print(nn)
oo=random.choice([2,3,4,5],size=(2,3))
print(oo)


0
0.2653614175507636
[[ 55  96 103  92   5 157]]
[[0.27063902 0.77064724 0.35572424 0.85141252 0.63462768 0.43568635]
 [0.77302192 0.44917881 0.08082161 0.73024002 0.6648027  0.3624523 ]]
[[4 4 2]
 [3 4 3]]


In [ ]:
from numpy import random

X = random.choice([1,2,3,4], p=[0.3, 0.3, 0.3, 0.1], size=(3,2))

print(X)


[[1 3]
 [3 3]
 [2 1]]


In [ ]:
from numpy import random

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)



[1 4 3 2 5]


In [ ]:
from numpy import random

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
random.permutation(arr)
print(arr)


[1 2 3 4 5]


Shuffle changes the original array but permutation doesn't.